name: ovn
adopt-info: ovn
grade: devel
summary: Open Virtual Network
description: |
  OVN, the Open Virtual Network, is a system to support virtual network
  abstraction.  OVN complements the existing capabilities of OVS to add
  native support for virtual network abstractions, such as virtual L2 and L3
  overlays, L4 load balancers and security groups.
confinement: strict
base: core18
apps:
  # NOTE: The OVS and OVN commands allow both outgoing and incoming connections
  # even the client commands.  Add both `network` and `network-bind` plugs.
  appctl:
    command: bin/ovn-appctl
    plugs:
      - network
      - network-bind
  controller:
    command: commands/controller
    daemon: forking
    plugs:
      - network
      - network-bind
      - openvswitch
  controller-vtep:
    command: commands/controller_vtep
    daemon: forking
    plugs:
      - network
      - network-bind
      - openvswitch
  detrace:
    command: bin/ovn-detrace
    plugs:
      - network
      - network-bind
  docker-overlay-driver:
    command: bin/ovn-docker-overlay-driver
    plugs:
      - network
      - network-bind
  docker-underlay-driver:
    command: bin/ovn-docker-underlay-driver
    plugs:
      - network
      - network-bind
  nbctl:
    command: bin/ovn-nbctl
    plugs:
      - network
      - network-bind
  northd:
    command: commands/northd
    daemon: forking
    plugs:
      - network
      - network-bind
  sbctl:
    command: bin/ovn-sbctl
    plugs:
      - network
      - network-bind
  trace:
    command: bin/ovn-trace
    plugs:
      - network
      - network-bind
  nb-ovsdb:
    environment:
      OVN_DBDIR: $SNAP_COMMON/var/lib/ovn
    command: commands/nb_ovsdb
    daemon: forking
    plugs:
      - network
      - network-bind
  sb-ovsdb:
    environment:
      OVN_DBDIR: $SNAP_COMMON/var/lib/ovn
    command: commands/sb_ovsdb
    daemon: forking
    plugs:
      - network
      - network-bind
parts:
  commands:
    source: snap/local/commands
    plugin: dump
    organize:
      '*': commands/
  openvswitch:
    source: https://github.com/openvswitch/ovs.git
    plugin: autotools
    configflags:
      - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/etc
      - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/var
      - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
    override-build: |
      ./boot.sh
      snapcraftctl build
      # make check TESTSUITEFLAGS="-j$SNAPCRAFT_PARALLEL_BUILD_COUNT"
      tar -cvzf $SNAPCRAFT_STAGE/openvswitch.tar.gz .
    build-packages:
      - autoconf
      - binutils
      - bsdmainutils
      - build-essential
      - gettext
      - git
      - libarchive-zip-perl
      - libcap-ng-dev
      - libpcap-dev
      - on arm64:
        - libnuma-dev
      - on ppc64el:
        - libnuma-dev
      - on amd64:
        - libdpdk-dev
        - libnuma-dev
        - librte-acl17.11
        - librte-bitratestats17.11
        - librte-bus-pci17.11
        - librte-bus-vdev17.11
        - librte-cfgfile17.11
        - librte-cmdline17.11
        - librte-cryptodev17.11
        - librte-distributor17.11
        - librte-eal17.11
        - librte-efd17.11
        - librte-ethdev17.11
        - librte-eventdev17.11
        - librte-flow-classify17.11
        - librte-gro17.11
        - librte-gso17.11
        - librte-hash17.11
        - librte-ip-frag17.11
        - librte-jobstats17.11
        - librte-kni17.11
        - librte-kvargs17.11
        - librte-latencystats17.11
        - librte-lpm17.11
        - librte-mbuf17.11
        - librte-member17.11
        - librte-mempool-octeontx17.11
        - librte-mempool-ring17.11
        - librte-mempool-stack17.11
        - librte-mempool17.11
        - librte-meter17.11
        - librte-metrics17.11
        - librte-net17.11
        - librte-pci17.11
        - librte-pdump17.11
        - librte-pipeline17.11
        - librte-pmd-af-packet17.11
        - librte-pmd-ark17.11
        - librte-pmd-avp17.11
        - librte-pmd-bnxt17.11
        - librte-pmd-bond17.11
        - librte-pmd-crypto-scheduler17.11
        - librte-pmd-cxgbe17.11
        - librte-pmd-e1000-17.11
        - librte-pmd-ena17.11
        - librte-pmd-enic17.11
        - librte-pmd-failsafe17.11
        - librte-pmd-fm10k17.11
        - librte-pmd-i40e17.11
        - librte-pmd-ixgbe17.11
        - librte-pmd-kni17.11
        - librte-pmd-lio17.11
        - librte-pmd-mlx4-17.11
        - librte-pmd-mlx5-17.11
        - librte-pmd-nfp17.11
        - librte-pmd-null-crypto17.11
        - librte-pmd-null17.11
        - librte-pmd-octeontx-ssovf17.11
        - librte-pmd-octeontx17.11
        - librte-pmd-pcap17.11
        - librte-pmd-qede17.11
        - librte-pmd-ring17.11
        - librte-pmd-sfc-efx17.11
        - librte-pmd-skeleton-event17.11
        - librte-pmd-softnic17.11
        - librte-pmd-sw-event17.11
        - librte-pmd-tap17.11
        - librte-pmd-thunderx-nicvf17.11
        - librte-pmd-vhost17.11
        - librte-pmd-virtio17.11
        - librte-pmd-vmxnet3-uio17.11
        - librte-port17.11
        - librte-power17.11
        - librte-reorder17.11
        - librte-ring17.11
        - librte-sched17.11
        - librte-security17.11
        - librte-table17.11
        - librte-timer17.11
        - librte-vhost17.11
      - libssl-dev
      - libtimedate-perl
      - libtool
      - libunbound-dev
      - pkg-config
      - python-all-dev
      - python-setuptools
      - python3-all-dev
      - python3-setuptools
      - python3-sphinx
      - sphinx-common
      - zlib1g-dev
    stage-packages:
      - libevent-2.1-6
      - libunbound2
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/share: /share
  ovn:
    after: [openvswitch]
    source: .
    plugin: autotools
    configflags:
      - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/etc
      - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/var
      - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
      - --with-ovs-source=$SNAPCRAFT_PART_BUILD/openvswitch
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
      rm -rf openvswitch
      mkdir openvswitch
      tar -C openvswitch -xvzf $SNAPCRAFT_STAGE/openvswitch.tar.gz
      rm -f $SNAPCRAFT_STAGE/openvswitch.tar.gz
    override-build: |
      ./boot.sh
      snapcraftctl build
      # make check TESTSUITEFLAGS="-j8 -k ovn"
    build-packages:
      - autoconf
      - binutils
      - build-essential
      - git
      - libssl-dev
      - libtool
      - python3-all-dev
      - sphinx-common
    stage-packages:
      - libevent-2.1-6
      - libunbound2
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/share: /share
    filesets:
      exclude-duplicate-manpages:
        - -share/man/man*/ovsdb*
    stage:
      - $exclude-duplicate-manpages
    prime:
      - $exclude-duplicate-manpages
